services:
  - type: web
    name: teleport-offramp
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    domains:
      - teleport.coinflow.cash
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
